apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::667104020309:role/eks-node-group-nodes
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::667104020309:role/CodeBuildKubectlRole
      username: CodeBuildKubectlRole
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-23T06:19:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "703308"
  uid: 4a1aeace-48ef-4c83-bb78-d28957b99b63
